services:
  backend:
    container_name: ugr-api
    image: billypl/ugr-backend:latest
    restart: always
    ports:
      - '5223:5223' # or use 443 if behind HTTPS proxy
    environment:
      - ASPNETCORE_URLS=http://+:5223;
      - ASPNETCORE_ENVIRONMENT=Production
      # convert to reverse proxy
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
      - ASPNETCORE_Kestrel__Certificates__Default__AllowInvalid=true
    depends_on:
      - db
    networks:
      - ugr-net

  frontend:
    container_name: ugr-frontend
    image: billypl/ugr-frontend:latest
    restart: always
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - ugr-net

  db:
    container_name: ugr-db
    image: postgres:17
    restart: always
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - ugr-net

  adminer:
    container_name: ugr-db-adminer
    image: adminer
    restart: always
    ports:
      - '${DB_ADMIN_PANEL_PORT}:${DB_ADMIN_PANEL_PORT}'
    networks:
      - ugr-net

networks:
  ugr-net:
