include:
  - docker-compose.infra.yaml
  - docker-compose.dev.yaml

services:
  backend:
    container_name: ugr-api
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src/UniGuesser.API
    ports:
      - '${BACKEND_PORT:-5223}:5223'
      - '7157:7157'
    volumes:
      - ../backend:/src
      - ../https:/https:ro

    environment:
      - ASPNETCORE_URLS=http://+:5223;https://+:7157
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev-cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
      - ASPNETCORE_ENVIRONMENT=Development
      - HOST_IP=${HOST_IP:-localhost}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}

    command: dotnet watch --project UniGuesser.API.csproj run
